export const magicServices = [
  {
    title: "Amarres de Amor",
    description: "Rituales poderosos para unir dos almas en un vínculo eterno, con resultados garantizados en días.",
    details: [
      "Recupera a tu ser amado en poco tiempo",
      "Fortalece vínculos existentes",
      "Elimina terceras personas",
      "Protección contra interferencias",
    ],
    icon: "heart",
    color: "from-rose-600 to-red-700",
    hoverColor: "from-rose-500 to-red-600",
    shadowColor: "rgba(225, 29, 72, 0.4)",
  },
  {
    title: "Limpieza Espiritual",
    description: "Rituales de purificación energética que eliminan bloqueos, maldiciones y energías negativas de tu vida.",
    details: [
      "Elimina bloqueos económicos y laborales",
      "Purifica espacios y personas",
      "Protección contra envidias",
      "Recupera tu energía vital",
    ],
    icon: "fire",
    color: "from-emerald-600 to-teal-700",
    hoverColor: "from-emerald-500 to-teal-600",
    shadowColor: "rgba(16, 185, 129, 0.4)",
    featured: true,
  },
  {
    title: "Videncia y Tarot",
    description: "Revelaciones precisas sobre tu pasado, presente y futuro a través de antiguas técnicas de adivinación.",
    details: [
      "Orientación en decisiones importantes",
      "Predicciones sobre amor y dinero",
      "Conexión con seres queridos",
      "Descubre tu destino y propósito",
    ],
    icon: "eye",
    color: "from-purple-600 to-indigo-700",
    hoverColor: "from-purple-500 to-indigo-600",
    shadowColor: "rgba(124, 58, 237, 0.4)",
  },
  {
    title: "Trabajos de Prosperidad",
    description: "Rituales ancestrales para atraer abundancia económica, éxito profesional y oportunidades.",
    details: [
      "Atrae nuevas oportunidades laborales",
      "Elimina la mala suerte en los negocios",
      "Potencia tus habilidades financieras",
      "Abre caminos para la prosperidad",
    ],
    icon: "money",
    color: "from-amber-600 to-yellow-700",
    hoverColor: "from-amber-500 to-yellow-600",
    shadowColor: "rgba(217, 119, 6, 0.4)",
  },
  {
    title: "Protección Espiritual",
    description: "Escudos místicos y talismanes poderosos que te protegen contra energías negativas y ataques espirituales.",
    details: [
      "Barrera contra maldiciones y hechizos",
      "Neutraliza influencias negativas",
      "Protege tu hogar y familia",
      "Amuletos personalizados y consagrados",
    ],
    icon: "shield",
    color: "from-blue-600 to-cyan-700",
    hoverColor: "from-blue-500 to-cyan-600",
    shadowColor: "rgba(14, 165, 233, 0.4)",
  },
  {
    title: "Endulzamientos",
    description: "Rituales dulces para suavizar corazones, mejorar relaciones y abrir caminos para la reconciliación.",
    details: [
      "Mejora relaciones familiares",
      "Suaviza actitudes hostiles",
      "Atrae personas con buenas intenciones",
      "Reconciliación con la pareja",
    ],
    icon: "heart",
    color: "from-pink-600 to-rose-700",
    hoverColor: "from-pink-500 to-rose-600",
    shadowColor: "rgba(219, 39, 119, 0.4)",
  },
]; 